### ISSUE TITLE
Rust Analyzer automatically removes valid generic args in GAT type constraint

### ISSUE THREAD

**Issue by b-naber** [rust-analyzer/rust-analyzer#10196]
In the following code rust analyzer automatically deletes code (the generic args on the associated type in the type constraint) that is necessary for the code to compile. This happens in the VS code extension.

```
#![feature(generic_associated_types)]

trait Trait {
    type Assoc<'a>;
}

// this requires a constraint on the associated type (Assoc<'a> = ()), but rust analyzer always automatically deletes the generic args on the associated type
fn f<'a, T: Trait<Assoc = ()>>(_: T, _: impl Fn(T::Assoc<'a>) -> T::Assoc<'a>) -> T::Assoc<'a> {}

struct Type;

impl Trait for Type {
    type Assoc<'a> = ();
}

fn main() {
    f(Type, |_| ());
}
```

**Comment by flodiebold** [comment]
If by "automatically" you mean when formatting, then this is a rustfmt bug. Does the same happen if you run `cargo fmt` in the command line?

**Comment by b-naber** [comment]
Yes that's what I meant, sorry for not being clear. This also happens when `cargo fmt` is run. I'll open an issue in the rustfmt repo.

**Comment by lnicola** [comment]
Which toolchain version are you using? This was fixed IIRC.

**Comment by b-naber** [comment]
I've updated to the latest nightly toolchain, but this still occurs.

**Comment by jonas-schievink** [comment]
Closing in favor of https://github.com/rust-lang/rustfmt/issues/4987
