### ISSUE TITLE
Completion stops working in macros

### ISSUE THREAD

**Issue by Matelasse** [rust-analyzer/rust-analyzer#2158]
Specifically in `prtinln!` macro.
In the following code where  ┃ is the cursor position
```rust
struct Test {
    i: char,
    t: i8,
    w: i8,
}
fn main() {
  let t = Test { i: 'a', t: 0, w: 0 };
  t.┃ // completion works here
  println!("{}", t.┃) // completion does not work here
}
```

**Comment by bjorn3** [comment]
That is expected, as something that looks like an expression to humans may not actually be an expression. It may in fact be a pattern or just some tokens.

**Comment by Matelasse** [comment]
@bjorn3 Well then can this be and few other macros be whitelisted, because you tend to want completion in `println!, format!, ...` and not seeing them makes you think that extension has stopped working.

**Comment by matklad** [comment]
Yeah, this is a known limitation at the moment. The crucial missing bit here is ability to correlate position in macro calls and in the expanded code. Shouldn't be too hard to implement, but will require quite a bit of plumbing throughout rust-analyzer.

**Comment by JoshMcguigan** [comment]
The example in the original post is now working, but it doesn't not work if the closing paren is left off.

```rust
struct Test {
    i: char,
    t: i8,
    w: i8,
}
fn main() {
  let t = Test { i: 'a', t: 0, w: 0 };
  t.┃ // completion works here
  println!("{}", t.┃ // completion does not work here, note the lack of closing paren
}
```

I made a small patch which fixes this [here](https://github.com/rust-analyzer/rust-analyzer/compare/master...JoshMcguigan:macro-completion-without-closing-parens), but I'm not sure it makes sense to fix this issue at the macro expansion level as opposed to fixing it earlier in the parsing. Thoughts on this?

**Comment by flodiebold** [comment]
That happens because the code [here](https://github.com/rust-analyzer/rust-analyzer/blob/21a35b49eea0750dffea0e1f7e7525e615951bf0/crates/ra_mbe/src/syntax_bridge.rs#L414-L419) only uses `(` as delimiter if there's a matching `)` in the end. We should probably be a bit more lenient there.

**Comment by edwin0cheng** [comment]
Yeah, that's definitely a bug in the place @flodiebold mentioned, and I think the approach in #3518 is much simpler than node/token based one used in there. I will try to factor it later.

**Comment by matklad** [comment]
the basics are fixed in master

**Comment by your-diary** [comment]
Has this actually been fixed? It seems the problem pointed out by @JoshMcguigan still exists. Or is this out of *basics*?
