### ISSUE TITLE
Unable to analyze lazy_static?

### ISSUE THREAD

**Issue by NichtsVonChaos** [rust-analyzer/rust-analyzer#3712]
```rust
use lazy_static::lazy_static;
lazy_static! {
    static ref VEC: Vec<u8> = vec![0x18u8, 0x11u8];
}

fn main() {
    let b = VEC.last();
}
```
`b` will be analyzed as `Option<{unknown}>`.

Using the lastest version from compiling lastest master branch. Is RA unable to  analyze lazy_static yet?

**Comment by edwin0cheng** [comment]
Seem like it is because we do not support `#[macro_export(local_inner_macros)]` yet. 

```rust
lazy_static! {
   static ref VEC: Vec<u8> = vec![0x18u8, 0x11u8];
}
```

The code above expanded to: (By command `Expand macro recursively`) 
```rust
__lazy_static_internal!(()static ref VEC:Vec<u8>  = vec![0x18u8,0x11u8];
);
```

And `__lazy_static_internal!` macro is defined as `#[macro_export(local_inner_macros)]`.

**Comment by edwin0cheng** [comment]
Fixed by #4305

OT: About 1 year ago, I started using rust-analyzer, but found that it cannot analyze `lazy_static`, but now it is finally done! 🎉

**Comment by teohhanhui** [comment]
If I understand correctly, this has been released in `2020-05-11`, right?

`Rust Analyzer: Show RA version`:
> rust-analyzer version: 2020-05-18 (31611da)

I'm still getting all the `{unknown}`s.

Code sample: https://users.rust-lang.org/t/immutable-object-design-pattern/42772/13

**Comment by teohhanhui** [comment]
Looks like I should use https://docs.rs/once_cell/1.4.0/once_cell/#lazy-initialized-global-data instead :smile:

**Comment by matklad** [comment]
Lol yes, at least partially,  the motivation for `once_cell`  was that IDEs at that time had troubles with `lazy_static!` :D

**Comment by edwin0cheng** [comment]
Yeah, @matklad is the best one to answer this question.

**Comment by matklad** [comment]
works on master

![Uploading image.png…]()

**Comment by bjorn3** [comment]
Image is broken

**Comment by FallenWarrior2k** [comment]
>Image is broken

Yes, the "Uploading image.png..." indicates the post was submitted before the image finished uploading.

In any case, `lazy_static!` in global scope seems to work, but when you have a `lazy_static!` block in a function, e.g. to keep implementation details inside, it still shows `{unknown}`.
I've tested this on nightly RA (`"rust-analyzer.updates.channel": "nightly"`), since the last comment was "works on master".

Compare:
![image](https://user-images.githubusercontent.com/20320149/92150484-c2557a00-ee1f-11ea-8ce8-c7fad839ec35.png)
![image](https://user-images.githubusercontent.com/20320149/92150596-ed3fce00-ee1f-11ea-9be7-ebe3d15e0d51.png)

Code for easy copy-pasting for those trying to repro:
Global:
```
use lazy_static::lazy_static;

lazy_static! {
    static ref VEC: Vec<u8> = vec![0u8, 1u8, 2u8];
}

fn main() {
    let x = VEC.last();
}
```

In function:
```
use lazy_static::lazy_static;

fn main() {
    lazy_static! {
        static ref VEC: Vec<u8> = vec![0u8, 1u8, 2u8];
    }

    let x = VEC.last();
}
```

**Comment by kiljacken** [comment]
That problem is presumably #1559
