### ISSUE TITLE
Odd location for implementation count text

### ISSUE THREAD

**Issue by rossmacarthur** [rust-analyzer/rust-analyzer#4461]
I have a "header" of sorts to separate code in the file into sections. And the implementation count for the first type below it is shown _above_ the header.

![image](https://user-images.githubusercontent.com/17109887/82024118-95723100-968f-11ea-888d-6b33c59656d0.png)

I think the highest line where it is placed should be based on the empty line.

**Comment by edwin0cheng** [comment]
It should be fixed by #4184 ?

**Comment by rossmacarthur** [comment]
Oh great, that's why I didn't find an open issue for this :+1:.

So I downloaded the nightly version of rust-analyzer and it didn't seem to fix anything 😞 

```
❯ ~/Library/ApplicationSupport/Code/User/globalStorage/matklad.rust-analyzer/rust-analyzer-mac --version
rust-analyzer 12d8268
