### ISSUE TITLE
IDE support in fn-like proc macro arguments

### ISSUE THREAD

**Issue by nitsky** [rust-analyzer/rust-analyzer#5265]
With support for fn-like proc macros as expressions becoming stable in rust 1.45 (https://github.com/rust-lang/rust/pull/68717), I am opening this issue to track rust-analyzer support for language features within them. 

For example, given the code below that uses a proc macro that implements jsx-like syntax...

```rust
let items = &["a", "b", "c"];
let html = html!(<ul>{items.iter().map(|item| html!(<li>{item}</li>))}</ul>);
```

... it would be awesome to be able to use "go to definition", "rename", "find references", etc when my cursor is over the last `item` identifier.

**Comment by nitsky** [comment]
Thanks to recent improvements by @jonas-schievink, language features in the example above now work perfectly. Thank you!

**Comment by i-schuetz** [comment]
@nitsky Which version? I'm using Rust-Analyzer v0.2.489 and Yew 0.17, followed the intro tutorial in the docs, and it doesn't work.

**Comment by bjorn3** [comment]
Did you enable proc-macro support using

```jsonc
{
    "rust-analyzer.cargo.loadOutDirsFromCheck": true,
    "rust-analyzer.procMacro.enable": true,
}
```

**Comment by i-schuetz** [comment]
@bjorn3 no, just added it, but it didn't help.
my main problem is probably that the HTML macro isn't found:
> could not resolve macro `html`rust-analyzermacro-error

But I'm able to navigate to the macro itself.
```rust
#[proc_macro_hack]
pub fn html(input: TokenStream) -> TokenStream {
    let root = parse_macro_input!(input as HtmlRootVNode);
    TokenStream::from(quote! {#root})
}
```

any idea?

**Comment by nitsky** [comment]
@i-schuetz in my experience macro not found errors are resolved by reloading the editor.

**Comment by i-schuetz** [comment]
Hmm sadly still not working, I restarted VSCode multiple times and double checked that the settings are in the workspace's settings.json (added them to the user's as well just in case) and the macro still doesn't work
> could not resolve macro `html`rust-analyzer macro-error

**Comment by memoryruins** [comment]
`html!` uses `proc_macro_hack` https://docs.rs/yew/0.17.4/src/yew/lib.rs.html#101. which tends to cause that error due to lack of attribute macro support https://github.com/rust-analyzer/rust-analyzer/issues/6029. Oh, after visiting that issue again, looks like another `html!` issue https://github.com/rust-analyzer/rust-analyzer/issues/7221 was closed for that reason.

To silence those warnings for now, `"macro-error"` can be added to `"rust-analyzer.diagnostics.disabled"`

**Comment by nitsky** [comment]
@i-schuetz I am not seeing the issue because I am using an in-house `html!` macro, which does not use `proc_macro_hack`, and which we designed to ensure it emits the correct span information for `rust-analyzer`.

**Comment by i-schuetz** [comment]
Was able to fix it by using yew master https://github.com/yewstack/yew/issues/1754#
