### ISSUE TITLE
test not running on correct function

### ISSUE THREAD

**Issue by GopherJ** [rust-analyzer/rust-analyzer#6132]
![image](https://user-images.githubusercontent.com/33961674/95019164-2314e400-0664-11eb-86d8-8cabf9d80fcc.png)

![image](https://user-images.githubusercontent.com/33961674/95019174-2b6d1f00-0664-11eb-97b9-6841d9f3bb5b.png)

**Comment by GopherJ** [comment]
example code: https://github.com/casbin/casbin-rs/blob/9cc61d80d7ce965779f4821629353364de799433/src/enforcer.rs#L1285

**Comment by GopherJ** [comment]
RA can run test correctly when it's simple:

```
#[test]
```
macro

but it fails to run test on more complex case:

```
    #[cfg(not(target_arch = "wasm32"))]
    #[cfg_attr(
        all(feature = "runtime-async-std", not(target_arch = "wasm32")),
        async_std::test
    )]
    #[cfg_attr(
        all(feature = "runtime-tokio", not(target_arch = "wasm32")),
        tokio::test
    )]
```

**Comment by matklad** [comment]
yeah... We should fix it, but I think that requires `cfg_attrs` support, which is not there yet.

**Comment by bjorn3** [comment]
triage: Still doesn't work even with `rust-analyzer.experimental.procAttrMacros`.

**Comment by ChayimFriedman2** [comment]
This should work now.
