### ISSUE TITLE
Odd markdown language IDs

### ISSUE THREAD

**Issue by rwols** [rust-analyzer/rust-analyzer#6655]
Some docstrings use an odd markdown language ID:

````
```compile_fail,E0277
trait TraitExample {}
...
```
````

This causes our markdown parser to not recognize them as code blocks:

![](https://user-images.githubusercontent.com/22029477/99969988-80433100-2d9b-11eb-81f0-74f85a40f542.png)

Would you be willing to use the `rust` markdown language ID in all markdown code blocks?

Client: Sublime Text LSP

**Comment by predragnikolic** [comment]
FWIW, here is the response we got from the server when we hovered the word `String`:
```
:: --> rust-analyzer textDocument/hover(54): {'position': {'character': 20, 'line': 1}, 'textDocument': {'uri': 'file:///home/predrag/Documents/sandbox/rust/app/src/main.rs'}}
:: <<< rust-analyzer 54: {'contents': {'value': '\n```rust\nalloc::string\n```\n\n```rust\npub struct String\n```\n\n---\n\nA UTF-8 encoded, growable string.\n\nThe `String` type is the most common string type that has ownership over the\ncontents of the string. It has a close relationship with its borrowed\ncounterpart, the primitive [`str`](https://doc.rust-lang.org/nightly/std/primitive.str.html).\n\n# Examples\n\nYou can create a `String` from a literal string with [`String::from`](https://doc.rust-lang.org/nightly/alloc/string/struct.String.html#method.from):\n\n```rust\nlet hello = String::from("Hello, world!");\n```\n\nYou can append a [`char`](https://doc.rust-lang.org/nightly/std/primitive.char.html) to a `String` with the [`push`](https://doc.rust-lang.org/nightly/alloc/string/struct.String.html#method.push) method, and\nappend a [`&str`](https://doc.rust-lang.org/nightly/std/primitive.str.html) with the [`push_str`](https://doc.rust-lang.org/nightly/alloc/string/struct.String.html#method.push_str) method:\n\n```rust\nlet mut hello = String::from("Hello, ");\n\nhello.push(\'w\');\nhello.push_str("orld!");\n```\n\nIf you have a vector of UTF-8 bytes, you can create a `String` from it with\nthe [`from_utf8`](https://doc.rust-lang.org/nightly/alloc/string/struct.String.html#method.from_utf8) method:\n\n```rust\n// some bytes, in a vector\nlet sparkle_heart = vec![240, 159, 146, 150];\n\n// We know these bytes are valid, so we\'ll use `unwrap()`.\nlet sparkle_heart = String::from_utf8(sparkle_heart).unwrap();\n\nassert_eq!("💖", sparkle_heart);\n```\n\n# UTF-8\n\n`String`s are always valid UTF-8. This has a few implications, the first of\nwhich is that if you need a non-UTF-8 string, consider [`OsString`](https://doc.rust-lang.org/nightly/std/ffi/struct.OsString.html). It is\nsimilar, but without the UTF-8 constraint. The second implication is that\nyou cannot index into a `String`:\n\n```compile_fail,E0277\nlet s = "hello";\n\nprintln!("The first letter of s is {}", s[0]); // ERROR!!!\n```\n\nIndexing is intended to be a constant-time operation, but UTF-8 encoding\ndoes not allow us to do this. Furthermore, it\'s not clear what sort of\nthing the index should return: a byte, a codepoint, or a grapheme cluster.\nThe [`bytes`](https://doc.rust-lang.org/nightly/alloc/string/struct.String.html#method.bytes) and [`chars`](https://doc.rust-lang.org/nightly/alloc/string/struct.String.html#method.chars) methods return iterators over the first\ntwo, respectively.\n\n# Deref\n\n`String`s implement [`Deref`](https://doc.rust-lang.org/nightly/std/ops/trait.Deref.html)`<Target=str>`, and so inherit all of [`str`](https://doc.rust-lang.org/nightly/std/primitive.str.html)\'s\nmethods. In addition, this means that you can pass a `String` to a\nfunction which takes a [`&str`](https://doc.rust-lang.org/nightly/std/primitive.str.html) by using an ampersand (`&`):\n\n```rust\nfn takes_str(s: &str) { }\n\nlet s = String::from("Hello");\n\ntakes_str(&s);\n```\n\nThis will create a [`&str`](https://doc.rust-lang.org/nightly/std/primitive.str.html) from the `String` and pass it in. This\nconversion is very inexpensive, and so generally, functions will accept\n[`&str`](https://doc.rust-lang.org/nightly/std/primitive.str.html)s as arguments unless they need a `String` for some specific\nreason.\n\nIn certain cases Rust doesn\'t have enough information to make this\nconversion, known as [`Deref`](https://doc.rust-lang.org/nightly/std/ops/trait.Deref.html) coercion. In the following example a string\nslice [`&\'a str`](https://doc.rust-lang.org/nightly/std/primitive.str.html) implements the trait `TraitExample`, and the function\n`example_func` takes anything that implements the trait. In this case Rust\nwould need to make two implicit conversions, which Rust doesn\'t have the\nmeans to do. For that reason, the following example will not compile.\n\n```compile_fail,E0277\ntrait TraitExample {}\n\nimpl<\'a> TraitExample for &\'a str {}\n\nfn example_func<A: TraitExample>(example_arg: A) {}\n\nlet example_string = String::from("example_string");\nexample_func(&example_string);\n```\n\nThere are two options that would work instead. The first would be to\nchange the line `example_func(&example_string);` to\n`example_func(example_string.as_str());`, using the method [`as_str()`](https://doc.rust-lang.org/nightly/alloc/string/struct.String.html#method.as_str)\nto explicitly extract the string slice containing the string. The second\nway changes `example_func(&example_string);` to\n`example_func(&*example_string);`. In this case we are dereferencing a\n`String` to a [`str`](https://doc.rust-lang.org/nightly/std/primitive.str.html), then referencing the [`str`](https://doc.rust-lang.org/nightly/std/primitive.str.html) back to\n[`&str`](https://doc.rust-lang.org/nightly/std/primitive.str.html). The second way is more idiomatic, however both work to do the\nconversion explicitly rather than relying on the implicit conversion.\n\n# Representation\n\nA `String` is made up of three components: a pointer to some bytes, a\nlength, and a capacity. The pointer points to an internal buffer `String`\nuses to store its data. The length is the number of bytes currently stored\nin the buffer, and the capacity is the size of the buffer in bytes. As such,\nthe length will always be less than or equal to the capacity.\n\nThis buffer is always stored on the heap.\n\nYou can look at these with the [`as_ptr`](https://doc.rust-lang.org/nightly/alloc/string/struct.String.html#method.as_ptr), [`len`](https://doc.rust-lang.org/nightly/alloc/string/struct.String.html#method.len), and [`capacity`](https://doc.rust-lang.org/nightly/alloc/string/struct.String.html#method.capacity)\nmethods:\n\n```rust\nuse std::mem;\n\nlet story = String::from("Once upon a time...");\n\n// Prevent automatically dropping the String\'s data\nlet mut story = mem::ManuallyDrop::new(story);\n\nlet ptr = story.as_mut_ptr();\nlet len = story.len();\nlet capacity = story.capacity();\n\n// story has nineteen bytes\nassert_eq!(19, len);\n\n// We can re-build a String out of ptr, len, and capacity. This is all\n// unsafe because we are responsible for making sure the components are\n// valid:\nlet s = unsafe { String::from_raw_parts(ptr, len, capacity) } ;\n\nassert_eq!(String::from("Once upon a time..."), s);\n```\n\nIf a `String` has enough capacity, adding elements to it will not\nre-allocate. For example, consider this program:\n\n```rust\nlet mut s = String::new();\n\nprintln!("{}", s.capacity());\n\nfor _ in 0..5 {\n    s.push_str("hello");\n    println!("{}", s.capacity());\n}\n```\n\nThis will output the following:\n\n```text\n0\n5\n10\n20\n20\n40\n```\n\nAt first, we have no memory allocated at all, but as we append to the\nstring, it increases its capacity appropriately. If we instead use the\n[`with_capacity`](https://doc.rust-lang.org/nightly/alloc/string/struct.String.html#method.with_capacity) method to allocate the correct capacity initially:\n\n```rust\nlet mut s = String::with_capacity(25);\n\nprintln!("{}", s.capacity());\n\nfor _ in 0..5 {\n    s.push_str("hello");\n    println!("{}", s.capacity());\n}\n```\n\nWe end up with a different output:\n\n```text\n25\n25\n25\n25\n25\n25\n```\n\nHere, there\'s no need to allocate more memory inside the loop.', 'kind': 'markdown'}, 'range': {'end': {'character': 24, 'line': 1}, 'start': {'character': 18, 'line': 1}}}

```

**Comment by bjorn3** [comment]
This is the full list of "language id"s recognized by rustdoc: https://github.com/rust-lang/rust/blob/36018a4d062fe30f0817685cab7b7ee2f2a367a8/src/librustdoc/html/markdown.rs#L823-L919

**Comment by matklad** [comment]
Yeah, we should fix it. Rust documentation format assumes `rust` as the default language, and adds various meta info after backtics. At the moment, we send md to the client mostly as is. Instead, we should restore the implied `rust` there, and probably strip rustdoc's meta.

**Comment by bjorn3** [comment]
This is now fixed it seems:
![image](https://user-images.githubusercontent.com/17426603/127856442-0ede770e-69d9-42c5-9cc0-b4ba0242e1ea.png)

I think the relevant PR's is https://github.com/rust-analyzer/rust-analyzer/pull/4915.

**Comment by flodiebold** [comment]
Hmm @bjorn3 are you sure? I don't see how that PR would affect the markdown on hover. And I think in VSCode this looked fine before as well?

**Comment by Veykril** [comment]
I think this got fixed with https://github.com/rust-analyzer/rust-analyzer/pull/5887?

**Comment by lnicola** [comment]
Well, both #5587 and #4915 are older than this issue.

**Comment by rwols** [comment]
It's generally still broken because the docs are not preprocessed. You can see it being cut off in the popup because the hrefs are not preprocessed. Same for the markdown language IDs for the code blocks. This is version 2021-08-2.

![image](https://user-images.githubusercontent.com/2431823/127924474-9e8eb655-382f-43d8-9a09-ffd90b51989f.png)

**Comment by Veykril** [comment]
Ye, that's a different problem, should be https://github.com/rust-analyzer/rust-analyzer/issues/8722
