### ISSUE TITLE
Macro invocation Error for simple dbg macro

### ISSUE THREAD

**Issue by edwin0cheng** [rust-analyzer/rust-analyzer#6716]
The following code shows an error of "failed to parse or resolve macro invocation" in master bb697727a

```rust
fn main() {
    dbg!("test");
}
```

**Comment by edwin0cheng** [comment]
in b988c6f84 , the errors are more explicit : 
```
could not resolve macro `$crate::file`
could not resolve macro `$crate::line`
could not resolve macro `$crate::stringify`
```

It seem like we couldn't resolve the `$crate` here.

**Comment by 0x7CFE** [comment]
In my case the issue also causes error flood in seemingly unrelated parts of the source file. For example, somewhere in the source I can have the following lines:

```rust
            let longs: HashSet<BitVector> = offset_codes.iter().cloned().collect();
            let shorts: HashSet<BitVector> = offset_codes.iter().map(|&b| contexts::hash(&[(b, 0.into())])).collect();
            dbg!(longs.len(), shorts.len());
```

And it causes the following errors within the same file:
<image src="https://user-images.githubusercontent.com/3784017/101149626-c75ddb80-3651-11eb-8652-61198e538e4b.png" width="50%" height="50%">

**Comment by villem** [comment]
Exactly same thing happens to me with the latest nightly
INFO [12/6/2020, 10:16:45 AM]: PersistentState: {
  lastCheck: 1607242597294,
  releaseId: 34886999,
  serverVersion: '0.3.405-nightly'
}
INFO [12/6/2020, 10:16:51 AM]: Using server binary at /Users/.../Library/Application Support/Code/User/globalStorage/matklad.rust-analyzer/rust-analyzer-mac

Commenting out dbg! removes the errors.

**Comment by Heliozoa** [comment]
I started getting this error after I updated to 0.2.408. Reverting to 0.2.400 fixes the issue. In addition to dbg!, usage of assert_eq! with a message seemed to cause this as well. I'm on Ubuntu 20.04.1 LTS and vscode
>Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:31:29.624Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-56-generic

if that's of any interest.

**Comment by Kungitoo** [comment]
Same thing for me. Started happening today out of nowhere.

![image](https://user-images.githubusercontent.com/6378638/101357596-f23a7080-3899-11eb-8a22-e96ad39864fb.png)

**Comment by unbornchikken** [comment]
Just wanted to confirm the above reports. I have issues by using 0.2.408 with genawaiter macros on Windows. Reverting back to 0.2.400 resolved the issue.

**Comment by lnicola** [comment]
The warning can be disabled using:

```json
"rust-analyzer.diagnostics.disabled": [
  "macro-error"
]
```

At this point there's no need for more confirmations.

**Comment by jonas-schievink** [comment]
The issue is that path resolution only looks at non-legacy macros, but `$crate::m` can also refer to legacy macros.

**Comment by jonas-schievink** [comment]
`ModPath { kind: Plain, segments: [Name(Text("$crate")), Name(Text("arg"))] }` :thinking: 

Reproduction:

```rust
#[macro_export]
#[rustc_builtin_macro]
macro_rules! format_args {}

#[macro_export]
macro_rules! arg {}

#[macro_export]
macro_rules! outer {
    () => {
        $crate::format_args!( "", $crate::arg!() )
    };
}

fn f() {
    outer!();
  //^^^^^^^^ leftover tokens
}
```

**Comment by jonas-schievink** [comment]
The resolution error should now be fixed. I'll look into the misplaced diagnostics later.

**Comment by danieljl** [comment]
Thanks @jonas-schievink! Is a new hotfix version going to be released? Or will this fix only be released on the next weekly release (6 days from now)?

**Comment by lnicola** [comment]
You can use the nightly version, but I'd suggest manually replacing the LSP binary or waiting until tomorrow because of a Code extension bug related to the update functionality (#6757).

Or you could disable the warning.

**Comment by jonas-schievink** [comment]
(the misplaced diagnostics are now also fixed)

**Comment by jeromegn** [comment]
The misplaced diagnostics are now gone, but I still get a "failed to parse macro invocation" error with the latest nightly. This is doing a `tokio::pin!` invocation.

**Comment by Victor-Savu** [comment]
Same as @jeromegn , I am still getting the error on the nightly version of rust-analyzer, in my case in a call to `futures::try_join!`.

**Comment by msrd0** [comment]
I just compiled the `rust-analyzer-git` package on ArchLinux, but I'm still seeing _failed to parse macro invocation_ for my invocation of the `serde_json::json!` macro.

**Comment by ibraheemdev** [comment]
Was this fixed with the latest stable release?

**Comment by msrd0** [comment]
Nope, still the same error message on the stable from yesterday.

**Comment by villem** [comment]
This is much better now, but I get "unresolved import" error when with  `use derive_more::Display;`
I'm using the latest nightly as of Dec 20.

**Comment by lnicola** [comment]
@villem that's a different issue. `derive_more` seems to be using a proc macro attribute, and those aren't supported yet (#6029).

Of course, you can still disable the diagnostic.

**Comment by villem** [comment]
@lnicola ok. This warning appeared in few days nightly build back. Maybe last week, so I got confused.
I'll probably disable the warning for now.
