### ISSUE TITLE
unexpected token in input when proptest! in file

### ISSUE THREAD

**Issue by Eh2406** [rust-analyzer/rust-analyzer#6747]
I just updated my rust analyzer, and now every file (at least in this project) gets the error `unexpected token in input`. The project is https://github.com/pubgrub-rs/pubgrub, and @lnicola can reproduce. They think it is the use of `proptest!`. I don't know how to be more helpful.

cc https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/unexpected.20token.20in.20input

**Comment by crumblingstatue** [comment]
I don't know if it's the same bug, but my advent of code project has the same bug in every solution in src/bin because of the macro usage
https://github.com/crumblingstatue/advent-of-code

**Comment by Eh2406** [comment]
BTW the suggestion here https://www.reddit.com/r/rust/comments/k8fo7w/rustanalyzer_changelog_54/gexzaem/?utm_source=reddit&utm_medium=web2x&context=3 got the meseges to go way so I can use rust-analyzer untill this is fixed.

**Comment by tensor-programming** [comment]
Had the same issue; can confirm that the suggestion removes the problem for now.  In my case, the error was `could not convert tokens` and this is for a very simple macro that just uses `concat!`, `file!()` and `line!()` to create a simple error code.

```
#[macro_export]
macro_rules! line_error {
    () => {
        concat!("Error at ", file!(), ":", line!())
    };
    ($str:expr) => {
        concat!($str, " @", file!(), ":", line!())
    };
}
```

**Comment by jonas-schievink** [comment]
The `concat!` issue, as well as the misplaced diagnostics, are now fixed.

**Comment by lnicola** [comment]
This seems to work fine now:

![image](https://user-images.githubusercontent.com/308347/101618099-2d63ad80-3a1a-11eb-914c-27540fd2586b.png)

There might still be some resolution errors on the enum variants in `Term::is_positive`, but that's a different issue.

**Comment by Eh2406** [comment]
I just updated my version of rust-analyzer and removed the change in settings. And this is still happening. It is no longer every file, it is no longer at the top. But every call to `proptest!` gets `unexpected token in input`.

**Comment by lnicola** [comment]
Repro:

```rust
macro_rules! foo {
    () => {{
        let _ = concat!(module_path!(), "::");
    }};
}

fn main() {
    foo! {}
}
```

**Comment by jonas-schievink** [comment]
Even just `concat!(module_path!(), "::");` is enough

**Comment by jonas-schievink** [comment]
Oh, we simply do not implement `module_path!()`.
