### ISSUE TITLE
Method of wrong trait chosen when two traits have the same method names and cyclic associated types

### ISSUE THREAD

**Issue by x-hgg-x** [rust-analyzer/rust-analyzer#9507]
Rust-analyzer chooses a method of the wrong trait in the following example:

```rust
pub trait Before {}

pub trait Left {
    type RightType: Right;

    fn method(&self) -> u64;
}

pub trait Between {}

pub trait Right {
    type LeftType: Left;

    fn method(&self, arg: u8) -> u8;
}

pub trait After {}

pub trait Trait {
    type Type: Left;
}

pub fn f<T: Trait>(x: &T::Type) {
    let _r = x.method();
}

fn main() {}
```

![screenshot](https://user-images.githubusercontent.com/39058530/124570636-5d0b5480-de47-11eb-9c35-8e18214eb008.png)

If the traits `Before`, `Between` and `After` are commented out, the inference is correct again.

Note: the inference seems to change randomly if VSCode is restarted, if another module is created or if a trait is renamed, but this example should be reproductible.

I'm using the latest release of rust-analyzer (rust-analyzer version: e5c1c8cf2 2021-07-05 stable) with the latest version of the vscode extension (0.2.662), on a Ubuntu 20.04 x64 system.

**Comment by lnicola** [comment]
I can't reproduce this, so it might have been fixed recently?

But it's worrying if it's non-deterministic.

**Comment by Veykril** [comment]
I can reproduce it on the latest nightly...

**Comment by x-hgg-x** [comment]
I can also reproduce on the latest nightly, so the problem is still there.

**Comment by lnicola** [comment]
Yeah, on Linux I see it too most of the time.

**Comment by ChayimFriedman2** [comment]
Works fine now.
