### ISSUE TITLE
Detect Cargo.toml changes from `cargo add`

### ISSUE THREAD

**Issue by MarenFayre** [rust-analyzer/rust-analyzer#9546]
**platform:** Windows 10 / VSCode 1.58.0 / RA v0.2.662

I like to use the command `cargo add` from cargo-edit to add dependencies to my projects but still need to manually touch the Cargo.toml file for RA to load its symbols. It would be nice if RA could detect those changes automatically.

**Comment by lnicola** [comment]
This should have been fixed in #9426 (included in 0.2.662), and I can't reproduce it, even on Windows. Would you mind setting `"rust-analyzer.trace.server": "verbose"` and watching the "Rust Analyzer Language Server Trace" output channel while you run `cargo add`?

We ask Code on start-up to watch for changes to `Cargo.toml` and it should send a notification when it does.

**Comment by MarenFayre** [comment]
This is running the following:

```
cargo add anyhow
cargo add rand 
cargo add winapi --features winuser
cargo feature winapi +dsound
```

**Trace:** [trace.txt](https://github.com/rust-analyzer/rust-analyzer/files/6795241/trace.txt)

I noticed a pattern where RA only seems to detect the first change to the Cargo.toml.
Every time I close and reopen VScode, the first `cargo add` or `cargo feature +` command will work, but none after that.
Maybe the watcher unsets itself after use or something?

**Comment by MarenFayre** [comment]
I just did a clean reinstall of vscode and the pattern is still the same on my side. Only the first change to the file is detected

**Comment by lnicola** [comment]
Yeah, I can confirm. Code does send a `workspace/didChangeWatchedFiles` notification (with 7 duplicate entries FWIW) and we do something in response, so I'm not sure what's wrong.

**Comment by lnicola** [comment]
So I'm not sure how it's supposed to work, but the code is here: https://github.com/rust-analyzer/rust-analyzer/blob/c9b4ac5be4daaabc062ab1ee663eba8594750003/crates/rust-analyzer/src/global_state.rs#L160-L206.

On the first `cargo add`, the `Cargo.toml` file seems to not be present in the VFS, so we take the `has_fs_changes` path. `fs_changes` is then passed to `maybe_refresh`, which triggers a workspace reload.

On a subsequent `cargo add`, we get a `Modify` change, so we don't append it to `fs_changes` and call `maybe_refresh` with an empty slice.

**Comment by lnicola** [comment]
Yeah, commenting out the `file.is_created_or_deleted()` seems to fix this without introducing project reloads when saving or adding a new file.

@matklad maybe you remember what's happening here?

**Comment by matklad** [comment]
Yeah, I think the case which makes this tricky that just “detect any change” is typing in `main.rs`. If you create or delete main.rs (or similar top-level files), we should reload everything. But for typing in main, we never need to do a reload.

logic for Cargo.toml and Cargo.lock is different, there, we need to reload even on content changes.

I guess we should teach maybe_refresh to distinguish between content and presence changes

**Comment by lnicola** [comment]
> But for typing in main, we never need to do a reload.

That might already be fine because `maybe_refresh` checks that `change_kind` isn't `Modify` for `main.rs` and the other files.

**Comment by jplatte** [comment]
This is really annoying, what do I have to do to get it fixed?

**Comment by lnicola** [comment]
@jplatte maybe you can test https://github.com/rust-analyzer/rust-analyzer/pull/10199 to see if it helps or breaks anything.

**Comment by jplatte** [comment]
Don't have time to look into how to build RA myself right now, but will try to do that over the coming days. Thanks for the quick response!

**Comment by lnicola** [comment]
Building it is a simple `cargo xtask install`. If you're using Code you can also wait about 6-8 hours and configure it to use the nightly update channel.
